#!/usr/bin/env bash
# Automatically creates and starts the systemd service
SERVICE_PATH="/etc/systemd/system/wyoming-kokoro.service"
WORKING_DIR=$(pwd)

sudo bash -c "cat > $SERVICE_PATH" <<EOF
[Unit]
Description=Wyoming Kokoro
After=network.target

[Service]
Type=simple
User=%U
WorkingDirectory=/opt/kokoro-wyoming
# Default environment variables
Environment="LD_LIBRARY_PATH=/usr/local/cuda/lib64"
Environment="KOKORO_ARGS=--uri tcp://0.0.0.0:10200"

# Using the variable in ExecStart
ExecStart=/opt/kokoro-wyoming/.venv/bin/python3 wyoming_kokoro.py $KOKORO_ARGS
Restart=always

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable wyoming-kokoro
sudo systemctl start wyoming-kokoro
echo "Service installed and started!"
